language: python

sudo : required
services:
  - docker

before_install:
  - docker pull dhigras/atmcorr-env:latest
  - mkdir private_dependencies
  - git clone git@github.com:DHI-GRAS/atmcorr_testdata.git private_dependencies/atmcorr_testdata

install:
  - docker build -t testenv -f Dockerfile.testing .

script:
  - docker run -it testenv "python -m pytest -v --runslow"
