language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda env create -f environment.yml
  - source activate atmcorr
  - conda install rasterio -c conda-forge/label/dev
  - conda install pytest
  - git clone git@github.com:DHI-GRAS/atmcorr_testdata.git
  - pushd atmcorr_testdata
  - pip install .
  - popd
  - pip install -e .
  - conda info -a

script:
    python -m pytest -v --runslow
