language: python

branches:
  only:
    - master

sudo : required

services:
  - docker

before_install:
  - docker pull dhigras/atmcorr-env:latest

install:
  - docker build -t testenv -f Dockerfile.testing .

script:
  - docker run -it testenv "python -m pytest -v --runslow"

notifications:
  email: false
  slack:
    rooms:
      - dhigras:TPwMxNqVS9FeaTUJNZlMmL6i
    on_failure: change
    on_success: change
    on_pull_requests: false
