FROM dhigras/atmcorr-env:latest

MAINTAINER Jonas Sølvsteen <josl@dhigroup.com>

WORKDIR /work

COPY private_dependencies private_dependencies
RUN ls -l private_dependencies && \
    for dir in private_dependencies/*/; do \
      echo $dir && \
      pip install -q $dir; \
    done

COPY . atmcorr
RUN ls -l atmcorr
RUN pip install -q ./atmcorr

WORKDIR /work/atmcorr
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["python -m pytest -v"]
