FROM dhigras/atmcorr-env:latest

MAINTAINER Jonas Sølvsteen <josl@dhigroup.com>

WORKDIR /work

COPY . atmcorr
RUN ls -l atmcorr
RUN pip install -q ./atmcorr

WORKDIR /work/atmcorr
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["python -m pytest -v"]
