name: atmcorr
channels:
    - conda-forge
    - default
    - conda-forge/label/dev
dependencies:
    - python=3
    - pyproj
    - rasterio>=1.0a12
    - gdal
    - numpy
    - scipy
    - click
    - ruamel.yaml
    - Py6S
    - lxml
    - shapely
    - tqdm
    - pandas  # sensor response curves
    - pip:
        - https://github.com/DHI-GRAS/yamlconfig/archive/master.zip
        - https://github.com/DHI-GRAS/satmeta/archive/master.zip
        - https://github.com/DHI-GRAS/sensor_response_curves/archive/master.zip
        - https://github.com/DHI-GRAS/dg-calibration/archive/master.zip
