name: atmcorr
channels:
    - conda-forge
dependencies:
    - python=3
    - gdal
    - rasterio
    - numpy
    - scipy
    - pandas
    - click
    - ruamel.yaml
    - Py6S
    - pyproj
    - lxml
    - shapely
    - tqdm
    - pip:
        - https://github.com/DHI-GRAS/yamlconfig/archive/master.zip
        - https://github.com/DHI-GRAS/satmeta/archive/master.zip
        - https://github.com/DHI-GRAS/sensor_response_curves/archive/master.zip
        - https://github.com/DHI-GRAS/dg-calibration/archive/master.zip
