name: atmcorr
channels:
    - conda-forge
dependencies:
    - python=2
    - gdal
    - numpy
    - scipy
    - pandas
    - tqdm
    - click
    - ruamel.yaml
    - Py6S
    - pip:
        - https://github.com/DHI-GRAS/gdal_utils/archive/master.zip
        - https://github.com/DHI-GRAS/yamlconfig/archive/master.zip
